/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum STATUS {
  LUA_OK = 0,
  LUA_YIELD = 1,
  LUA_ERRRUN = 2,
  LUA_ERRSYNTAX = 3,
  LUA_ERRMEM = 4,
  LUA_ERRERR = 5
}
export const enum GARBAGE_COLLECTION {
  LUA_GCSTOP = 0,
  LUA_GCRESTART = 1,
  LUA_GCCOLLECT = 2,
  LUA_GCCOUNT = 3,
  LUA_GCCOUNTB = 4,
  LUA_GCSTEP = 5,
  LUA_GCSETPAUSE = 6,
  LUA_GCSETSTEPMUL = 7,
  LUA_GCSETMAJORINC = 8,
  LUA_GCISRUNNING = 9,
  LUA_GCGEN = 10,
  LUA_GCINC = 11
}
export type JsLuaEngine = Lua
export class Lua {
  constructor()
  openLibs(): void
  doString(script: string): STATUS
  doFile(path: string): number
  pushString(value: string): string
  pushNumber(value: number): void
  pushInteger(value: number): void
  pushBoolean(value: number): void
  pushNil(): void
  setGlobal(value: string): void
  getGlobal(value: string): number
  getType(value: number): number
  toString(value: number): string
  toNumber(value: number): number
  toBoolean(value: number): boolean
  getTop(): number
  setTop(value: number): void
  replace(value: number): void
  pop(value: number): void
  setField(value: number, value2: string): void
  getField(value: number, value2: string): number
  yield(value: number): number
  collectGarbage(what: GARBAGE_COLLECTION, data: number): number
  status(): number
  Resume(value: number, value2: number): number
  close(): void
}
